---
- name: Install python-pip
  package:
    name: python-pip
    state: present

- name: Install python-dev
  package:
    name: python-dev
    state: present

- name: Install docker-py via pip
  pip:
    name: docker

# NOTE(kiennt): Ansible docker module uses docker-compose as python library
#               so that docker-compose execuable file won't work in this case.
#               We have to install docker-compose via pip.
- name: Install docker-compose via pip
  pip:
    name: docker-compose

- name: Create prompose directory
  file:
    path: "{{ prompose_path }}"
    state: "directory"
    mode: 0777
  become: true

- name: Copy docker-compose file
  template:
    src: "prompose/docker-compose.yml.j2"
    dest: "{{ prompose_path }}/docker-compose.yml"
    mode: 0777

- name: Ensure grafana provisioning - datasources exists
  file:
    path: "{{ prompose_path }}/grafana/provisioning/datasources"
    state: "directory"
    mode: 0777
  become: true
  when:
    - inventory_hostname in groups['grafana']
    - enable_grafana | bool

- name: Copy grafana datasources
  template:
    src: "prompose/grafana/provisioning/datasources/datasource.yml.j2"
    dest: "{{ prompose_path }}/grafana/provisioning/datasources/datasource.yml.j2"
    mode: 0644
  when:
    - inventory_hostname in groups['grafana']
    - enable_grafana | bool

- name: Ensure grafana provisioning - dashboards exists
  file:
    path: "{{ prompose_path }}/grafana/provisioning/dashboards"
    state: "directory"
    mode: 0777
  become: true
  when:
    - inventory_hostname in groups['grafana']
    - enable_grafana | bool

- name: Copy grafana dashboards
  copy:
    src: "{{ item }}"
    dest: "{{ prompose_path }}/grafana/provisioning/dashboards/"
  with_fileglob:
    - "../templates/prompose/grafana/provisioning/dashboards/*"
  when:
    - inventory_hostname in groups['grafana']
    - enable_grafana | bool

- name: Ensure prometheus directory exists
  file:
    path: "{{ prompose_path }}/prometheus"
    state: "directory"
    mode: 0777
  become: true
  when:
    - inventory_hostname in groups['prometheus']

- name: Copy prometheus.yml config
  template:
    src: "prompose/prometheus/prometheus.yml.j2"
    dest: "{{ prompose_path }}/prometheus/prometheus.yml"
    mode: 0644
  when:
    - inventory_hostname in groups['prometheus']

- name: Copy alert.rules
  copy:
    src: "../templates/prompose/prometheus/alert.rules"
    dest: "{{ prompose_path }}/prometheus/alert.rules"
    mode: 0644
  when:
    - inventory_hostname in groups['prometheus']

- name: Ensure alertmanager directory exists
  file:
    path: "{{ prompose_path }}/alertmanager"
    state: "directory"
    mode: 0777
  become: true
  when:
    - inventory_hostname in groups['alertmanager']

- name: Copy alert config
  template:
    src: "prompose/alertmanager/config.yml.j2"
    dest: "{{ prompose_path }}/alertmanager/config.yml"
    mode: 0644
  when:
    - inventory_hostname in groups['alertmanager']

