---
- name: Create prompose directory
  file:
    path: "{{ prompose_path }}"
    state: "directory"
    mode: 0755
  become: true

- name: Copy docker-compose file
  template:
    src: "prompose/docker-compose.yml.j2"
    dest: "{{ prompose_path }}/docker-compose.yml"
    mode: 0755

- name: Ensure grafana provisioning - datasources exists
  file:
    path: "{{ prompose_path }}/grafana/provisioning/datasources"
    state: "directory"
    mode: 0755
  become: true
  when:
    - inventory_hostname in groups['grafana']
    - enable_grafana | bool

- name: Copy grafana datasources
  template:
    src: "prompose/grafana/provisioning/datasources/datasource.yml.j2"
    dest: "{{ prompose_path }}/grafana/provisioning/datasources/datasource.yml.j2"
    mode: 0644
  when:
    - inventory_hostname in groups['grafana']
    - enable_grafana | bool

- name: Copy grafana dashboards
  template:
    src: "prompose/grafana/provisioning/dashboards"
    dest: "{{ prompose_path }}/grafana/provisioning/dashboards"
    mode: 0644
  when:
    - inventory_hostname in groups['grafana']
    - enable_grafana | bool

- name: Ensure prometheus directory exists
  file:
    path: "{{ prompose_path }}/prometheus"
    state: "directory"
    mode: 0755
  become: true
  when:
    - inventory_hostname in groups['prometheus']

- name: Copy prometheus.yml config
  template:
    src: "prompose/prometheus/prometheus.yml.j2"
    dest: "{{ prompose_path }}/prometheus/prometheus.yml"
    mode: 0644
  when:
    - inventory_hostname in groups['prometheus']

- name: Copy alert.rules
  template:
    src: "prompose/prometheus/alert.rules"
    dest: "{{ prompose_path }}/prometheus/alert.rules"
    mode: 0644
  when:
    - inventory_hostname in groups['prometheus']

- name: Ensure alertmanager directory exists
  file:
    path: "{{ prompose_path }}/alertmanager"
    state: "directory"
  become: true
  when:
    - inventory_hostname in groups['alertmanager']

- name: Copy alert config
  template:
    src: "prompose/alertmanager/config.yml.j2"
    dest: "{{ prompose_path }}/alertmanager/config.yml"
    mode: 0644
  when:
    - inventory_hostname in groups['alertmanager']

- name: Run docker-compose
    project_src "{{ prompose_path }}"
    state: present
    recreate: "smart"
