---

- name: Stop and remove all prompose containers
  docker_service:
    project_src: "{{ prompose_path }}"
    state: absent
    remove_volumes: "{{ remove_volumes }}"

- name: Remove all images
  docker_service:
    project_src: "{{ prompose_path }}"
    state: absent
    remove_images: "all" # value of remove_images must be one of: all, local, not yes no options.
  when: remove_images
