---

- name: Stop and remove all prompose containers
  docker_service:
    project_src: "{{ prompose_path }}"
    state: absent
    remove_images: "{{ remove_images }}"
    remove_volumes: "{{ remove_volumes }}"
