---

- name: Stop and remove all prompose containers (Without remove images)
  docker_service:
    project_src: "{{ prompose_path }}"
    state: absent
    remove_volumes: "{{ remove_volumes }}"
  when: not remove_images | bool

- name: Stop, remove all prompose containers and images
  docker_service:
    project_src: "{{ prompose_path }}"
    state: absent
    remove_images: "all" # value of remove_images must be one of: all, local, not yes no options.
    remove_volumes: "{{ remove_volumes }}"
  when: remove_images | bool
