---
- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker
  package:
    name: "{{ docker_pkg }}"
    state: "{{ docker_pkg_state }}"
  when: install_docker | bool

- name: Remove Upstart config file
  file:
    path: "/etc/default/docker"
    state: absent

- name: Ensure systemd directory exists
  file:
    path: "/etc/systemd/system"
    state: directory
    owner: root
    mode: 0755

- name: Ensure docker directory exists
  file:
    path: "/etc/docker"
    state: directory
    owner: root
    mode: 0755

- name: Change system unit template in RHEL/CentOS
  set_fact:
    docker_systemd_template: 'docker.service.rpm.j2'
  when: ansible_os_family == 'RedHat'

- name: Generate systemd unit file
  template:
    src: "{{ docker_systemd_template }}"
    dest: "/etc/systemd/system/docker.service"
    owner: root
    group: root
    mode: 0644
  register: docker_register_systemd_service

- name: Generate docker daemon configure file
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: 0644
  register: docker_register_daemon

- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  notify: Restart docker
  when: (docker_register_systemd_service and
         docker_register_systemd_service | changed) or
        (docker_register_daemon and
         docker_register_daemon | changed)

- name: Ensure Docker is stared and enabled at boot
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Add specfic users to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: True
  with_items: "{{ docker_users }}"
  when: docker_users

- name: Install Docker compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "{{ docker_compose_path }}"
    force: True
    owner: root
    group: root
    mode: 0755
  when: install_docker_compose | bool
